# Generated by Django 6.0.6 on 2026-06-20 07:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('journal_type', models.CharField(choices=[('trading', 'Trading'), ('backtest', 'Backtest')], default='trading', max_length=20)),
                ('starting_capital', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('break_even_method', models.CharField(choices=[('ratio', 'Ratio'), ('profit', 'Profit')], default='ratio', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmotionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_tags', to='core.journal')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.journal')),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='MistakeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_tags', to='core.journal')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SetupTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_tags', to='core.journal')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('entry_datetime', models.DateTimeField()),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('risk_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pnl_r', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('swap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opportunity_timeframe', models.CharField(blank=True, max_length=10, null=True)),
                ('entry_timeframe', models.CharField(blank=True, max_length=10, null=True)),
                ('trend_direction', models.CharField(blank=True, choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('RANGE', 'Range')], max_length=20, null=True)),
                ('session', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('BE', 'Break Even')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='core.asset')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.journal')),
                ('setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='core.setuptag')),
            ],
            options={
                'ordering': ['-entry_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emotiontag')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trade')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='emotions',
            field=models.ManyToManyField(through='core.TradeEmotion', to='core.emotiontag'),
        ),
        migrations.CreateModel(
            name='TradeMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mistaketag')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trade')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='mistakes',
            field=models.ManyToManyField(blank=True, through='core.TradeMistake', to='core.mistaketag'),
        ),
        migrations.CreateModel(
            name='TradeScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trade_screenshots/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.trade')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_journal_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('journal', 'symbol'), name='unique_asset_symbol_per_journal'),
        ),
        migrations.AlterUniqueTogether(
            name='tradeemotion',
            unique_together={('trade', 'emotion')},
        ),
        migrations.AlterUniqueTogether(
            name='trademistake',
            unique_together={('trade', 'mistake')},
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['journal', 'entry_datetime'], name='core_trade_journal_15f790_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['journal', 'status'], name='core_trade_journal_fdc216_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['journal', 'asset'], name='core_trade_journal_bebc17_idx'),
        ),
    ]
