# Generated by Django 6.0.6 on 2026-06-11 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=50)),
                ('trend_direction', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('RANGE', 'Range')], max_length=20)),
                ('opportunity_timeframe', models.CharField(choices=[('MN', 'Monthly'), ('W1', 'Weekly'), ('D1', 'Daily'), ('H4', '4 Hour'), ('H1', '1 Hour'), ('M15', '15 Minute'), ('M5', '5 Minute')], max_length=5)),
                ('entry_timeframe', models.CharField(choices=[('MN', 'Monthly'), ('W1', 'Weekly'), ('D1', 'Daily'), ('H4', '4 Hour'), ('H1', '1 Hour'), ('M15', '15 Minute'), ('M5', '5 Minute')], max_length=5)),
                ('setup', models.CharField(max_length=100)),
                ('session', models.CharField(choices=[('ASIA', 'Asia'), ('LONDON', 'London'), ('NEW_YORK', 'New York')], max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WIN', 'Win'), ('LOSS', 'Loss'), ('BE', 'Break even')], default='OPEN', max_length=10)),
                ('entry_datetime', models.DateTimeField()),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('risk_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pnl_r', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('emotion', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trade_screenshots/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.trade')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['owner', 'entry_datetime'], name='core_trade_owner_i_a128bd_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['owner', 'status'], name='core_trade_owner_i_6bcc46_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['owner', 'asset'], name='core_trade_owner_i_63a029_idx'),
        ),
    ]
