# Generated by Django 6.0.6 on 2026-06-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='break_even_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
