# Generated by Django 6.0.6 on 2026-06-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_importbatch_tradeimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='format_detected',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='raw_rows_found',
            field=models.IntegerField(default=0),
        ),
    ]
