# Generated by Django 6.0.6 on 2026-06-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_import_batch_diagnostics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
